#!/usr/bin/env bash
# =============================================================================
# generate-configs.sh — 从 deploy/config.yaml 生成所有节点的 .env 文件
#
# 输出: generated/controller.env, generated/<node_id>.env
#
# 依赖: python3 -c "import yaml" (或 pip install pyyaml)
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
CONFIG_FILE="${SCRIPT_DIR}/config.yaml"
OUTPUT_DIR="${ROOT_DIR}/generated"

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'

if [[ ! -f "$CONFIG_FILE" ]]; then
    echo "ERROR: $CONFIG_FILE not found"
    exit 1
fi

# ========== 检查 Python + PyYAML ==========
if ! python3 -c "import yaml" 2>/dev/null; then
    echo "Installing PyYAML..."
    pip3 install pyyaml -q
fi

mkdir -p "$OUTPUT_DIR"

# ========== 读取 YAML ==========
eval "$(python3 -c "
import yaml, json, os, secrets

with open('$CONFIG_FILE', 'r') as f:
    cfg = yaml.safe_load(f)

# 共享密钥
secret = cfg['global']['shared_secret']
if secret == 'auto':
    secret = secrets.token_hex(32)

# Controller URL
ctrl_host = cfg['controller']['host']
ctrl_port = cfg['controller']['port']
controller_url = f'https://{ctrl_host}:{ctrl_port}'

# 环境变量导出
lines = []
lines.append(f'SHARED_SECRET={secret}')
lines.append(f'ALLOWED_TARGET_CIDRS={",".join(cfg[\"global\"][\"allowed_target_cidrs\"])}')
lines.append(f'GLOBAL_MAX_RPS={cfg[\"global\"][\"global_max_rps\"]}')
lines.append(f'GLOBAL_MAX_PPS={cfg[\"global\"][\"global_max_pps\"]}')
lines.append(f'GLOBAL_MAX_CONCURRENT={cfg[\"global\"][\"global_max_concurrent\"]}')
lines.append(f'CONTROLLER_URL={controller_url}')
lines.append(f'CONTROLLER_IP={ctrl_host}')
lines.append(f'LOG_LEVEL={cfg[\"global\"][\"log_level\"]}')

# Controller 专属
ctrl = cfg['controller']
lines.append(f'CONTROLLER_HOST=0.0.0.0')
lines.append(f'CONTROLLER_PORT={ctrl_port}')
lines.append(f'ENABLE_WEB_UI={\"true\" if ctrl.get(\"enable_web_ui\", True) else \"false\"}')
lines.append(f'DEPLOY_METHOD_CONTROLLER={ctrl[\"deploy_method\"]}')

# 写入 controller.env
with open('${OUTPUT_DIR}/controller.env', 'w') as f:
    f.write('# Generated by generate-configs.sh\n')
    f.write(f'# Controller URL: {controller_url}\n\n')
    for line in lines:
        f.write(line + '\n')

# Attacker 节点
for atk in cfg.get('attackers', []):
    node_id = atk['node_id']
    node_lines = list(lines)
    node_lines.append(f'NODE_ID={node_id}')
    node_lines.append(f'NODE_TYPE={atk[\"type\"]}')
    node_lines.append(f'DEPLOY_METHOD={atk[\"deploy_method\"]}')
    node_lines.append(f'ATTACK_TYPES={",".join(atk[\"attacks\"])}')
    if atk['type'] == 'http':
        node_lines.append(f'MAX_RPS={atk.get(\"max_rps\", 10000)}')
        node_lines.append(f'MAX_CONCURRENT={atk.get(\"max_concurrent\", 5000)}')
    else:
        node_lines.append(f'MAX_PPS={atk.get(\"max_pps\", 50000)}')
        node_lines.append(f'MAX_CONCURRENT={atk.get(\"max_concurrent\", 1000)}')
        node_lines.append(f'NETWORK_INTERFACE={atk.get(\"network_interface\", \"eth0\")}')
    labels = ','.join(f'{k}={v}' for k,v in atk.get('labels', {}).items())
    node_lines.append(f'NODE_LABELS={labels}')
    node_lines.append(f'INSTALL_DIR={atk.get(\"install_dir\", \"/opt/ddos-attack-platform/attacker\")}')

    outfile = f'${OUTPUT_DIR}/{node_id}.env'
    with open(outfile, 'w') as f:
        f.write(f'# Generated by generate-configs.sh\n')
        f.write(f'# Node: {node_id}  |  Type: {atk[\"type\"]}  |  Deploy: {atk[\"deploy_method\"]}\n')
        f.write(f'# Controller: {controller_url}\n\n')
        for line in node_lines:
            f.write(line + '\n')

print(f'Generated configs in ${OUTPUT_DIR}/')
print(f'  Shared secret length: {len(secret)} bytes')
print(f'  Controller URL: {controller_url}')
print(f'  Nodes: {len(cfg.get(\"attackers\", []))}')
" 2>&1)"

# ========== 输出结果 ==========
echo -e "${GREEN}=== Configuration files generated ===${NC}"
echo ""
ls -la "$OUTPUT_DIR"/
echo ""
echo -e "${YELLOW}Next steps:${NC}"
echo "  1. Review generated configs:  ls generated/"
echo "  2. Generate certificates:      make certs"
echo "  3. Distribute certs + configs: ./deploy/distribute-certs.sh"
echo "  4. Deploy:                     ./deploy/unified-deploy.sh deploy-all"