#!/usr/bin/env bash
# =============================================================================
# DDoS Attack Platform — Linux 二进制一键部署 + systemd 服务安装
# 
# 用法:
#   sudo ./install-service.sh controller       # 仅安装 Controller
#   sudo ./install-service.sh attacker         # 安装 HTTP Attacker
#   sudo ./install-service.sh attacker-raw     # 安装 RAW Attacker (需要 root)
#
# 环境变量覆盖:
#   INSTALL_DIR=/opt/ddos-attack-platform       # 安装目录
#   CONTROLLER_URL=https://10.100.1.10:8443    # Attacker 连哪个 Controller
#   SHARED_SECRET=...                           # 预共享密钥
# =============================================================================

set -euo pipefail

ROLE="${1:-}"
if [[ -z "$ROLE" ]]; then
    echo "Usage: $0 <controller|attacker|attacker-raw>"
    exit 1
fi

# ========== 配置 ==========
INSTALL_DIR="${INSTALL_DIR:-/opt/ddos-attack-platform}"
SERVICE_USER="${SERVICE_USER:-ddos}"
SERVICE_NAME="ddos-${ROLE}"
BINARY_NAME="ddos-${ROLE%%-*}"  # controller/attacker

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
log_info()  { echo -e "${GREEN}[INFO]${NC} $*"; }
log_warn()  { echo -e "${YELLOW}[WARN]${NC} $*"; }
log_error() { echo -e "${RED}[ERROR]${NC} $*"; }

# ========== 前置检查 ==========
if [[ $EUID -ne 0 ]]; then
    log_error "This script must be run as root (sudo)"
    exit 1
fi

if [[ ! -f "./${BINARY_NAME}" ]]; then
    log_error "Binary not found: ./${BINARY_NAME}"
    log_error "Place the release tarball contents in the current directory first"
    exit 1
fi

# ========== 创建用户 ==========
if ! id -u "${SERVICE_USER}" &>/dev/null; then
    log_info "Creating service user: ${SERVICE_USER}"
    useradd -r -s /usr/sbin/nologin -m -d /nonexistent "${SERVICE_USER}"
fi

# ========== 安装目录 ==========
TARGET_DIR="${INSTALL_DIR}/${ROLE%%-*}"  # controller/ or attacker/
log_info "Installing to: ${TARGET_DIR}"
mkdir -p "${TARGET_DIR}" "${TARGET_DIR}/certs"

# 复制文件
cp -f "./${BINARY_NAME}" "${TARGET_DIR}/"
chmod 755 "${TARGET_DIR}/${BINARY_NAME}"

if [[ -f "./config.env" ]]; then
    cp -f "./config.env" "${TARGET_DIR}/config.env"
fi

# 场景文件 (仅 Controller)
if [[ "$ROLE" == "controller" ]] && [[ -d "./scenarios" ]]; then
    cp -rf "./scenarios" "${TARGET_DIR}/"
fi

# ========== 权限 ==========
chown -R "${SERVICE_USER}:${SERVICE_USER}" "${TARGET_DIR}"

# ========== 环境变量配置文件 ==========
ENV_FILE="${TARGET_DIR}/config.env"
if [[ ! -f "${ENV_FILE}" ]]; then
    # C-3 修复: 禁止自动生成随机密钥 — Controller 与所有 Attacker 必须共享
    # 同一个 SHARED_SECRET, 各节点独立生成会导致认证体系整体失效。
    if [[ -z "${SHARED_SECRET:-}" ]]; then
        log_error "SHARED_SECRET is required but not set."
        log_error "Generate once and reuse on EVERY node:  export SHARED_SECRET=\$(openssl rand -hex 32)"
        exit 1
    fi
    if [[ "${SHARED_SECRET}" == changeme* ]] || [[ ${#SHARED_SECRET} -lt 32 ]]; then
        log_error "SHARED_SECRET must be at least 32 chars and not a 'changeme' placeholder."
        exit 1
    fi
    log_info "Creating default config.env"
    cat > "${ENV_FILE}" <<EOF
# Generated by install-service.sh at $(date -Iseconds)
SHARED_SECRET=${SHARED_SECRET}
ALLOWED_TARGET_CIDRS=${ALLOWED_TARGET_CIDRS:-10.100.0.0/16,192.168.0.0/16}
CONTROLLER_URL=${CONTROLLER_URL:-https://10.100.1.10:8443}
EOF
    chown "${SERVICE_USER}:${SERVICE_USER}" "${ENV_FILE}"
    chmod 600 "${ENV_FILE}"
    log_warn "Please edit ${ENV_FILE} with your actual configuration"
fi

# ========== systemd 服务 ==========
SERVICE_FILE="${TARGET_DIR}/${SERVICE_NAME}.service"
if [[ -f "./${SERVICE_NAME}.service" ]]; then
    cp -f "./${SERVICE_NAME}.service" "${SERVICE_FILE}"
elif [[ -f "/tmp/${SERVICE_NAME}.service" ]]; then
    cp -f "/tmp/${SERVICE_NAME}.service" "${SERVICE_FILE}"
else
    log_warn "systemd unit file not found, generating default..."
    # 生成默认 unit
    cat > "${SERVICE_FILE}" <<UNIT
[Unit]
Description=DDoS Attack Platform - ${ROLE}
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=${SERVICE_USER}
Group=${SERVICE_USER}
WorkingDirectory=${TARGET_DIR}
ExecStart=${TARGET_DIR}/${BINARY_NAME}
Restart=always
RestartSec=10
EnvironmentFile=-${TARGET_DIR}/config.env
StandardOutput=journal
StandardError=journal
SyslogIdentifier=${SERVICE_NAME}
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target
UNIT
fi

# 安装 systemd 服务
cp -f "${SERVICE_FILE}" "/etc/systemd/system/${SERVICE_NAME}.service"
systemctl daemon-reload

# ========== 启动 ==========
log_info "Starting ${SERVICE_NAME}..."
systemctl enable "${SERVICE_NAME}"
systemctl start "${SERVICE_NAME}" || {
    log_error "Failed to start ${SERVICE_NAME}"
    journalctl -u "${SERVICE_NAME}" --no-pager -n 20
    exit 1
}

# ========== 验证 ==========
sleep 2
if systemctl is-active --quiet "${SERVICE_NAME}"; then
    log_info "✓ ${SERVICE_NAME} is running"
    systemctl status "${SERVICE_NAME}" --no-pager -l
else
    log_error "✗ ${SERVICE_NAME} failed to start"
    journalctl -u "${SERVICE_NAME}" --no-pager -n 30
    exit 1
fi

echo ""
echo "========================================="
echo "  Installation complete!"
echo "========================================="
echo ""
echo "  Service:     ${SERVICE_NAME}"
echo "  Binary:      ${TARGET_DIR}/${BINARY_NAME}"
echo "  Config:      ${TARGET_DIR}/config.env"
echo ""
echo "  Commands:"
echo "    systemctl status ${SERVICE_NAME}"
echo "    systemctl restart ${SERVICE_NAME}"
echo "    journalctl -u ${SERVICE_NAME} -f"
echo ""
case "$ROLE" in
    controller)
        echo "  API:         https://$(hostname -I | awk '{print $1}'):8443/docs"
        echo "  Health:      https://$(hostname -I | awk '{print $1}'):8443/health"
        ;;
    attacker*)
        echo "  API:         http://$(hostname -I | awk '{print $1}'):8080/health"
        echo "  Metrics:     http://$(hostname -I | awk '{print $1}'):8080/metrics"
        ;;
esac
echo ""